version: 0.2

env:
  variables:
    TERRAFORM_VERSION: "1.0.6"
  secrets-manager:
    GITHUB_PERSONAL_TOKEN: "MAC_REQUIRED_CREDENTIALS:AMWAYACS_GITHUB_PERSONAL_TOKEN"

phases:
  install:
    runtime-versions:
      python: 3.7
    on-failure: ABORT       
    commands:
      - tf_version=$TERRAFORM_VERSION
      - wget https://releases.hashicorp.com/terraform/"$TERRAFORM_VERSION"/terraform_"$TERRAFORM_VERSION"_linux_amd64.zip
      - unzip terraform_"$TERRAFORM_VERSION"_linux_amd64.zip
      - mv terraform /usr/local/bin/
  pre_build:
    on-failure: ABORT     
    commands:
      - chmod +x $CODEBUILD_SRC_DIR/SRE-MAC-CLIENT-CODE/scripts/prebuild.sh && $CODEBUILD_SRC_DIR/SRE-MAC-CLIENT-CODE/scripts/prebuild.sh          
  build:
    on-failure: ABORT   
    commands:
      - TF_COMMAND=`cat temp.txt`
      - cd "$CODEBUILD_SRC_DIR/main/app"
      - ls -lrt "$CODEBUILD_SRC_DIR/main/app"
      - terraform --version
      - echo "check state.conf file present!!" && ls -lta $CODEBUILD_SRC_DIR/code-build/
      - terraform init -input=false --upgrade --backend-config=$CODEBUILD_SRC_DIR/state.conf
      - terraform validate
      - terraform plan -lock=false -input=false       
      - terraform $TF_COMMAND -input=false -auto-approve
      
  post_build:
    on-failure: CONTINUE   
    commands:
      - echo $CODEBUILD_BUILD_ID terraform execution completed on `date`      