version: 0.2

env:
  variables:
    TERRAFORM_VERSION: "1.0.6"
  secrets-manager:
    GITHUB_PERSONAL_TOKEN: "MAC_REQUIRED_CREDENTIALS:AMWAYACS_GITHUB_PERSONAL_TOKEN"
    CF_USER: "MAC_REQUIRED_CREDENTIALS:CF_USER"
    CF_PASSD: "MAC_REQUIRED_CREDENTIALS:CF_PASSD"

phases:
  install:
    runtime-versions:
      python: 3.7
    on-failure: ABORT       
    commands:
      - tf_version=$TERRAFORM_VERSION
      - wget https://releases.hashicorp.com/terraform/"$TERRAFORM_VERSION"/terraform_"$TERRAFORM_VERSION"_linux_amd64.zip
      - unzip terraform_"$TERRAFORM_VERSION"_linux_amd64.zip
      - mv terraform /usr/local/bin/
  pre_build:
    on-failure: ABORT     
    commands:
      - chmod +x $CODEBUILD_SRC_DIR/SRE-MAC-CLIENT-CODE/scripts/read_tf_output.py
      - chmod +x $CODEBUILD_SRC_DIR/SRE-MAC-CLIENT-CODE/scripts/codebuild.sh 
      - $CODEBUILD_SRC_DIR/SRE-MAC-CLIENT-CODE/scripts/codebuild.sh prebuild    
  build:
    on-failure: ABORT   
    commands:
      - $CODEBUILD_SRC_DIR/SRE-MAC-CLIENT-CODE/scripts/codebuild.sh build
      
  post_build:
    on-failure: CONTINUE   
    commands:
      - chmod +x $CODEBUILD_SRC_DIR/SRE-MAC-CLIENT-CODE/scripts/run_py.sh 
      - $CODEBUILD_SRC_DIR/SRE-MAC-CLIENT-CODE/scripts/run_py.sh  
      - echo $CODEBUILD_BUILD_ID terraform execution completed on `date`      